spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${PG_HOST:localhost}:${PG_PORT:5432}/${PG_DATABASE:channeling}
    username: ${PG_USER}
    password: ${PG_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 1
    locations: classpath:db/migration
    schemas: public

  session:
    store-type: redis   # 세션 저장소 Redis로 지정
    timeout: 30m        # 세션 유지시간(옵션)

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: 6379
logging:
  config: classpath:logback-spring.xml
  discord:
    webhook-url: ${DISCORD_WEBHOOK_URL}