cloud:
  aws:
    region:
      static: ${AWS_REGION}
    credentials:
      access-key:  ${AWS_ACCESS_KEY_ID}
      secret-key: ${AWS_SECRET_ACCESS_KEY}


s3:
  private-bucket: ${AWS_S3_PRIVATE_BUCKET}
  public-bucket: ${AWS_S3_PUBLIC_BUCKET}
